name: birthdaycounter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  image_picker: ^1.2.1
  flutter_svg: ^2.2.3
  google_fonts: ^7.0.2
  google_sign_in: ^6.1.0
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/birthdaylogo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

# 🔥 APP ICON CONFIG (TOP LEVEL — VERY IMPORTANT)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/birthdaylogo.png"
  remove_alpha_ios: true
